import type { Metadata } from "next";
import { Provider } from "@/app/components/ui/Provider/provider";
import "./styles/globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Nav from "@/app/components/ui/Nav";

export const metadata: Metadata = {
  title: "Nodoka Hanaki's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  );
}
